### ISSUE TITLE
[BUG]: Updating Username 

### ISSUE THREAD

**Issue by ltodtuu** [mobile-directing-system/mds-desktop#55] opened 2022-07-14 08:56 UTC
### Bug Description

When updating the username a new user is created with the same id but a different username.

### Expected Behavior

old version should no longer exist

### Steps to Reproduce

update a users username.

### Possible Solutions

Problem possibly from the users list in the userstate.

**Comment by haasy** [comment] 2022-07-14 09:58
This bug is caused by checking if the usernames are the same in the addOrUpdateUser method. This check causes the user to be added to the user array instead of the existing one being updated. This is a remnant from early development where we thought it might be possible for users to exist without a id in the frontend (due to caching considered early in develpment).

This is fixed in 0ac1c93348a1b788b0f704bd126c8832c437d02b, by using the userId to check for object equality.

**Closed by haasy** 2022-07-14 09:58 UTC
Labels: scope:implementation, type:suggestion
